Repository kris701/MARMA, pull requests merged in 2023-11, with the labels that each got.

#70 Macro extractor changes
  MacroExtractor/Program.cs
  MacroExtractor/Properties/launchSettings.json
  MetaActions.Test/Program.cs
  MetaActions.Train/LearningTask.cs
  MetaActions.Train/Options.cs
  MetaActions.Train/Program.cs
  MetaActions.Train/Properties/launchSettings.json
Labels: refactorings

#72 feat: adds custom stackelberg
  Dependencies/setup_programs.sh
  MacroExtractor/MacroExtractor.csproj
  MacroExtractor/Program.cs
  MacroExtractor/Properties/launchSettings.json
  MacroExtractor/TestData/miconic/domain.pddl
  MacroExtractor/TestData/miconic/meta-1/0.plan
  MacroExtractor/TestData/miconic/meta-5/0.plan
  MacroExtractor/TestData/miconic/meta-5/1.plan
  MetaActionGenerator/Program.cs
  MetaActions.Train/LearningTask.cs
  MetaActions.Train/Options.cs
  MetaActions.Train/Program.cs
  MetaActions.Train/Properties/launchSettings.json
  StackelbergCompiler/ConditionalEffectCompiler.cs
  StackelbergCompiler/Properties/launchSettings.json
  StackelbergCompiler/ReservedNames.cs
  StackelbergVerifier/Properties/launchSettings.json
  Tools/PathHelper.cs
  reconstruction/src/cache/mod.rs
Labels: feature

#74 Removed meta actions that have the same effects as preconditions
  MetaActionGenerator/Program.cs
Labels: bug

#75 Graphs!
  Dependencies/setup_packages.sh
  MetaActions.Test/Options.cs
  MetaActions.Test/Program.cs
  MetaActions.Test/Properties/launchSettings.json
  MetaActions.Test/RunReport.cs
  MetaActions.Test/TestingTask.cs
  MetaActions.Train/Program.cs
  graphs.R
Labels: feature, testing

#76 Returns to fully lifted macros
  MacroExtractor/Program.cs
Labels: feature

#81 Fix for only outputting macros that have at least some effects
  MacroExtractor/Program.cs
Labels: bug

#83 Fixed for meta actions with "duplicated" parameters
  MacroExtractor/MacroExtractor.csproj
  MacroExtractor/Program.cs
  MacroExtractor/Properties/launchSettings.json
  MacroExtractor/TestData/floortile/domain.pddl
  MacroExtractor/TestData/floortile/meta-1/0231ec52-2fba-da9c-f39a-945a45967a1c.plan
  MacroExtractor/TestData/floortile/meta-1/12d107b8-7fa0-a707-cf19-dd8668003f28.plan
  MacroExtractor/TestData/floortile/meta-1/4c11fddb-4c15-e7c3-2756-ef2a8ca43fed.plan
  MacroExtractor/TestData/floortile/meta-1/71beb9ce-d615-40a2-711f-fe2e4b8f7752.plan
  MacroExtractor/TestData/floortile/meta-1/91b9aefc-7c99-ad08-92ac-c7e05876ef53.plan
  MacroExtractor/TestData/floortile/meta-1/ad601871-b935-cc28-594e-b55f8270af8f.plan
  MacroExtractor/TestData/floortile/meta-1/ad83216f-5414-62eb-3c47-38150ef930f9.plan
  MacroExtractor/TestData/floortile/meta-1/ebac746d-f8d5-4151-5156-b0ddd9feda85.plan
Labels: bug

#84 Set the coverage graph to use total time instead of search time
  P9.sln
  graphs.R
Labels: testing

#88 Larger refactoring of the `MetaActions.Test` project
  MetaActions.Test/Program.cs
  MetaActions.Test/Reconstructors/CacheReconstructor.cs
  MetaActions.Test/Reconstructors/FastDownwardReconstructor.cs
  MetaActions.Test/Reconstructors/IReconstructor.cs
  MetaActions.Test/Reconstructors/NoReconstructor.cs
  MetaActions.Test/TestingTask.cs
Labels: refactorings

#91 Generates generic parameter names for macros
  MacroExtractor/Program.cs
  MacroExtractor/RepairSequence.cs
Labels: bug

#94 Better help message with enums
  MetaActions.Test/Program.cs
  Tools/BaseCLI.cs
Labels: documentation

#95 Bugfix for sequential test run
  MetaActions.Test/Program.cs
Labels: bug

#97 Adds a prebuilder, that compiled everything
  .gitignore
  P9.sln
  PreBuilder/PreBuilder.csproj
  PreBuilder/Program.cs
  PreBuilder/Properties/launchSettings.json
  Tools/ArgsCallerBuilder.cs
Labels: testing

#105 Stackelberg Compiler handles constants, Meta Action Generator fixes, Tests
  MetaActionGenerator/CandidateGenerators/BaseMetaGenerator.cs
  MetaActionGenerator/CandidateGenerators/RemoveAdditionalEffects.cs
  MetaActionGenerator/CandidateGenerators/RemoveEffectParameters.cs
  MetaActionGenerator/CandidateGenerators/RemovePreconditionParameters.cs
  MetaActionGenerator/MetaActionGenerator.cs
  MetaActionGenerator/MetaActionGenerator.csproj
  MetaActionGenerator/Options.cs
  MetaActionGenerator/Program.cs
  MetaActionGenerator/Properties/launchSettings.json
  MetaActionGenerator/RemovePreconditionParameters.cs
  MetaActionGenerator/TestData/gripper-domain.pddl
  MetaActionGenerator/TestData/sokoban-macros/macro1.pddl
  MetaActions.Train/LearningTask.cs
  P9.sln
  StackelbergCompiler/ConditionalEffectCompiler.cs
  StackelbergVerifier/StackelbergVerifierOptions.cs
  Tests/MetaActionGenerator.Tests/CandidateGenerators/RemoveAdditionalEffectsTests.cs
  Tests/MetaActionGenerator.Tests/CandidateGenerators/RemoveEffectParametersTests.cs
  Tests/MetaActionGenerator.Tests/CandidateGenerators/RemovePreconditionParametersTests.cs
  Tests/MetaActionGenerator.Tests/GlobalUsings.cs
  Tests/MetaActionGenerator.Tests/MetaActionGenerator.Tests.csproj
  Tests/MetaActionGenerator.Tests/MetaActionGeneratorTests.cs
  Tests/MetaActionGenerator.Tests/TestData/satellite/domain.pddl
  Tests/MetaActionGenerator.Tests/TestData/sokoban/domain.pddl
Labels: bug, feature, testing

#112 Testing of the `StackelbergCompiler` and more testing sets
  P9.sln
  StackelbergCompiler/ConditionalEffectCompiler.cs
  StackelbergCompiler/ConditionalEffectSimplifyer.cs
  StackelbergCompiler/Options.cs
  StackelbergCompiler/Program.cs
  StackelbergCompiler/StackelbergCompiler.csproj
  StackelbergCompiler/StackelbergCompilerOptions.cs
  StackelbergCompiler/StaticPredicateDetector.cs
  StackelbergCompiler/TotalGoalGenerator.cs
  TestingSets/blocksworld_p01-p19.zip
  TestingSets/satellite_p01-p19.zip
  Tests/StackelbergCompiler.Tests/ConditionalEffectCompilerTests.cs
  Tests/StackelbergCompiler.Tests/ConditionalEffectSimplifyerTests.cs
  Tests/StackelbergCompiler.Tests/GlobalUsings.cs
  Tests/StackelbergCompiler.Tests/StackelbergCompiler.Tests.csproj
  Tests/StackelbergCompiler.Tests/StaticPredicateDetectorTests.cs
  Tests/StackelbergCompiler.Tests/TotalGoalGeneratorTests.cs
  Tools/GitFetcher.cs
Labels: testing, refactorings

#110 Updated some of the training sets to the new format
  TestingSets/floortile_p01-p19.zip
  TestingSets/miconic_p01-p19.zip
Labels: testing

#120 feat: adds cluster stuff
  Cluster Stuff/run.sh
  Cluster Stuff/scripts/fd_runner.sh
  Cluster Stuff/scripts/instance_runner.sh
  Cluster Stuff/scripts/ms_runner.sh
Labels: testing

#122 Bug fix for the macro extractor
  .gitignore
  MacroExtractor/MacroExtractor.cs
  MetaActions.Train/LearningTask.cs
  MetaActions.Train/Properties/launchSettings.json
  Tests/MacroExtractor.Tests/MacroExtractorTests.cs
Labels: bug

#123 Updated graphs
  MacroExtractor/MacroExtractor.cs
  MacroExtractor/RepairSequence.cs
  MetaActions.Train/LearningTask.cs
  TestingSets/satellite_p01-p19.zip
  Tests/MacroExtractor.Tests/MacroExtractorTests.cs
  graphs.R
Labels: data, testing

#129 Refactor reconstruction
  reconstruction/src/cache/generation.rs
  reconstruction/src/cache/hash_cache.rs
  reconstruction/src/cache/lifted.rs
  reconstruction/src/cache/mod.rs
  reconstruction/src/instance.rs
  reconstruction/src/instance/expression.rs
  reconstruction/src/instance/facts.rs
  reconstruction/src/instance/objects.rs
  reconstruction/src/instance/operator.rs
  reconstruction/src/instance/parameters.rs
  reconstruction/src/instance/permute.rs
  reconstruction/src/instance/types.rs
  reconstruction/src/main.rs
  reconstruction/src/reconstruction/downward_wrapper.rs
  reconstruction/src/state.rs
  reconstruction/src/tools/memory.rs
  reconstruction/src/world.rs
Labels: cleaning

#131 Adds an options to only output "useful" meta actions
  MetaActions.Train/LearningTask.cs
  MetaActions.Train/Options.cs
  MetaActions.Train/Program.cs
Labels: feature

#132 More aggressive meta action duplicate purge
  MetaActionGenerator/MetaActionGenerator.cs
  MetaActionGenerator/MetaActionGenerator.csproj
  MetaActionGenerator/Properties/launchSettings.json
  MetaActionGenerator/TestData/blocksworld-macros/0.pddl
  MetaActionGenerator/TestData/blocksworld-macros/1.pddl
  MetaActions.Train/LearningTask.cs
  Tests/MetaActionGenerator.Tests/MetaActionGeneratorTests.cs
Labels: bug

#134 PDDLSharp Macro Generator
  MetaActions.Train/LearningTask.cs
  MetaActions.Train/MetaActions.Train.csproj
  MetaActions.Train/Options.cs
  MetaActions.Train/Program.cs
  MetaActions.Train/Properties/launchSettings.json
  MetaActions.Train/RunReport.cs
  MetaActions.Train/Tools/IOHelper.cs
  MetaActions.Train/Trainers/BaseTrainer.cs
  MetaActions.Train/Trainers/CSMTrainer.cs
  MetaActions.Train/Trainers/ITrainer.cs
  MetaActions.Train/Trainers/PDDLSharpTrainer.cs
  StackelbergVerifier/Program.cs
  StackelbergVerifier/Properties/launchSettings.json
Labels: feature, refactorings

#137 feat: score calculator
  score_calculator/.gitignore
  score_calculator/Cargo.lock
  score_calculator/Cargo.toml
  score_calculator/src/input_handling.rs
  score_calculator/src/main.rs
  score_calculator/src/score_generation.rs
Labels: testing

#145 Updated graphs
  graphs.R
Labels: feature

#142 Various changes to reconstruction
  reconstruction/src/cache/hash_cache.rs
  reconstruction/src/cache/lifted.rs
  reconstruction/src/cache/mod.rs
  reconstruction/src/fact.rs
  reconstruction/src/instance.rs
  reconstruction/src/instance/actions.rs
  reconstruction/src/instance/expression.rs
  reconstruction/src/instance/facts.rs
  reconstruction/src/instance/objects.rs
  reconstruction/src/instance/operator.rs
  reconstruction/src/instance/parameters.rs
  reconstruction/src/instance/permute.rs
  reconstruction/src/instance/predicates.rs
  reconstruction/src/instance/types.rs
  reconstruction/src/main.rs
  reconstruction/src/reconstruction/problem_writing.rs
  reconstruction/src/reconstruction/reconstruction.rs
  reconstruction/src/state.rs
  reconstruction/src/tools/mod.rs
  reconstruction/src/world.rs
  reconstruction/tests/data/miconic/cache/$meta_11/macro1_replacement.plan
  reconstruction/tests/data/miconic/cache/$meta_11/macro2_replacement.plan
  reconstruction/tests/data/miconic/cache/$meta_5/macro1_replacement.plan
  reconstruction/tests/data/miconic/cache/$meta_5/macro2_replacement.plan
Labels: refactorings

#157 Cleanups
  MacroExtractor/MacroExtractor.cs
  MacroExtractor/Options.cs
  MacroExtractor/Program.cs
  MacroExtractor/RepairSequence.cs
  MetaActionGenerator/CandidateGenerators/RemovePreconditionParameters.cs
  MetaActionGenerator/MetaActionGenerator.cs
  MetaActionGenerator/Program.cs
  MetaActions.Test/MetaActions.Test.csproj
  MetaActions.Test/Options.cs
  MetaActions.Test/Program.cs
  MetaActions.Test/Properties/launchSettings.json
  MetaActions.Test/Reconstructors/CacheReconstructor.cs
  MetaActions.Test/Reconstructors/FastDownwardReconstructor.cs
  MetaActions.Test/Reconstructors/IReconstructor.cs
  MetaActions.Test/Reconstructors/NoReconstructor.cs
  MetaActions.Test/RunReport.cs
  MetaActions.Train/Options.cs
  MetaActions.Train/PreBuilder.cs
  MetaActions.Train/Program.cs
  MetaActions.Train/RunReport.cs
  MetaActions.Train/Tools/IOHelper.cs
  MetaActions.Train/Tools/ListHelper.cs
  MetaActions.Train/Trainers/BaseTrainer.cs
  MetaActions.Train/Trainers/CSMTrainer.cs
  MetaActions.Train/Trainers/ITrainer.cs
  MetaActions.Train/Trainers/PDDLSharpTrainer.cs
  P9.sln
  PreBuilder/PreBuilder.csproj
  PreBuilder/Program.cs
  PreBuilder/Properties/launchSettings.json
  StackelbergCompiler/ConditionalEffectCompiler.cs
  StackelbergCompiler/ConditionalEffectSimplifyer.cs
  StackelbergCompiler/StaticPredicateDetector.cs
  StackelbergCompiler/TotalGoalGenerator.cs
  Tests/MacroExtractor.Tests/MacroExtractorTests.cs
  Tests/MetaActionGenerator.Tests/CandidateGenerators/RemoveAdditionalEffectsTests.cs
  Tests/MetaActionGenerator.Tests/CandidateGenerators/RemoveEffectParametersTests.cs
  Tests/MetaActionGenerator.Tests/CandidateGenerators/RemovePreconditionParametersTests.cs
  Tests/MetaActionGenerator.Tests/MetaActionGeneratorTests.cs
  Tests/StackelbergCompiler.Tests/ConditionalEffectCompilerTests.cs
  Tests/StackelbergCompiler.Tests/ConditionalEffectSimplifyerTests.cs
  Tests/StackelbergCompiler.Tests/StaticPredicateDetectorTests.cs
  Tests/StackelbergCompiler.Tests/TotalGoalGeneratorTests.cs
  Tools/GitFetcher.cs
Labels: cleaning

#160 Even more graphs
  .gitignore
  Graphs/clamper.R
  Graphs/coveragePlots.R
  Graphs/domainBarPlots.R
  Graphs/donutPlots.R
  Graphs/graphNames.R
  Graphs/graphs.R
  Graphs/ipcGraphs.R
  Graphs/runall.sh
  Graphs/scatterPlots.R
  Graphs/style.R
  graphs.R
Labels: testing

#166 Iterative cache
  reconstruction/src/cache/generation.rs
  reconstruction/src/cache/hash.rs
  reconstruction/src/cache/lifted.rs
  reconstruction/src/cache/mod.rs
  reconstruction/src/fact.rs
  reconstruction/src/macro_generation.rs
  reconstruction/src/main.rs
  reconstruction/src/reconstruction/reconstruction.rs
  reconstruction/src/state.rs
  reconstruction/src/successor_genrator/mod.rs
  reconstruction/src/successor_genrator/static.rs
  reconstruction/src/world.rs
  reconstruction/src/world/action.rs
  reconstruction/src/world/parameter.rs
Labels: feature

#185 Large Graphs update
  .gitignore
  Dependencies/setup_packages.sh
  Graphs/ipcGraphs.R
  Graphs/reconstructionGraphs.R
  Graphs/runall.sh
  Graphs/src/clamper.R
  Graphs/src/coveragePlots.R
  Graphs/src/domainBarPlots.R
  Graphs/src/donutPlots.R
  Graphs/src/graphNames.R
  Graphs/src/scatterPlots.R
  Graphs/src/style.R
  Graphs/trainGraphs.R
Labels: feature, testing, refactorings
